# Generated by Django 2.2.6 on 2020-07-17 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200718_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='place_address',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
